version: '3'
services:
  php:
    build:
      context: ./docker/php-${PHP_VERSION:-7.4}
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP:-1000}'
        WWWUSER: '${WWWUSER:-1000}'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    expose:
      - "9000"
    volumes:
      - './www:/var/www'
      - './docker/logs/php:/var/log/php'
    networks:
      - bitrix-internal
#      - bitrix-external
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP:-1000}'
        WWWUSER: '${WWWUSER:-1000}'
    depends_on:
      - php
      - mysql
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - './www:/var/www'
      - './docker/logs/nginx:/var/log/nginx'
    networks:
      - bitrix-internal
      - bitrix-external
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'db-mysql:/var/lib/mysql'
      - './docker/mysql/my.cnf:/etc/mysql/my.cnf'
    networks:
      - bitrix-internal
      - bitrix-external
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-p${DB_PASSWORD}' ]
      retries: 3
      timeout: 5s

volumes:
  db-mysql:
    driver: local

networks:
  bitrix-internal:
    driver: bridge
    internal: true
  bitrix-external:
    driver: bridge

